export const LAYOUT_VIEW_SIZE = {
  MENUBAR_HEIGHT: 35,
  EDITOR_TABS_HEIGHT: 35,
  BIG_SUR_TITLEBAR_HEIGHT: 28,
  TITLEBAR_HEIGHT: 22,
  PANEL_TITLEBAR_HEIGHT: 35,
  STATUSBAR_HEIGHT: 24,
  ACCORDION_HEADER_SIZE_HEIGHT: 24,
};
