labels:
  '🐞 bug':
    - '\bfix:'
    - '\bfix('
  '🎨 feature':
    - '\bfeat:'
    - '\bfeat('
  '⚙️ refactor':
    - '\brefactor:'
    - '\brefactor('
  '💄 style change':
    - '\bstyle:'
    - '\bstyle('
  '📌 patch':
    - '\bpatch:'
    - '\bpatch('
