coverage:
  status:
    project:
      default:
        target: auto
        # allow coverage to drop by this amount and still post success
        threshold: 0.5%
        if_ci_failed: error
    patch:
      default:
        target: 0%
        if_ci_failed: error
        only_pulls: true
codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 4
    wait_for_ci: true
