[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
nixpacksPlan = { "providers" = ["node", "python"] }

[deploy]
numReplicas = 1
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
