import { AcpPermissionHandler, PermissionDecision } from '../../../lib/browser/acp/permission.handler';

// Mock @opensumi/di to make decorators no-ops
jest.mock('@opensumi/di', () => {
  const actual = jest.requireActual('@opensumi/di');
  const noopDecorator = () => () => {};
  return {
    ...actual,
    Injectable: () => (cls: any) => cls,
    Autowired: noopDecorator,
    Inject: noopDecorator,
    Optional: noopDecorator,
  };
});

// Mock dependencies
const mockLogger = {
  log: jest.fn(),
  error: jest.fn(),
  debug: jest.fn(),
  verbose: jest.fn(),
  warn: jest.fn(),
  critical: jest.fn(),
  dispose: jest.fn(),
  getLevel: jest.fn(),
  setLevel: jest.fn(),
};

const mockStorage = {
  get: jest.fn().mockReturnValue('[]'),
  set: jest.fn(),
  onUpdate: jest.fn(),
  dispose: jest.fn(),
};

const mockPreferenceService = {
  get: jest.fn(),
  set: jest.fn(),
  onPreferenceChanged: jest.fn(() => ({ dispose: jest.fn() })),
};

const mockStorageProvider = jest.fn().mockResolvedValue(mockStorage);

// Helper to capture the uuid generated by requestPermission
let capturedRequestId: string | undefined;
const originalUuid = jest.requireActual('@opensumi/ide-core-common').uuid;
let uuidCounter = 0;

jest.mock('@opensumi/ide-core-common', () => {
  const actual = jest.requireActual('@opensumi/ide-core-common');
  return {
    ...actual,
    uuid: () => {
      uuidCounter++;
      const id = `test-uuid-${uuidCounter}`;
      capturedRequestId = id;
      return id;
    },
  };
});

describe('AcpPermissionHandler', () => {
  let handler: AcpPermissionHandler;

  beforeEach(() => {
    jest.useFakeTimers();
    jest.clearAllMocks();
    mockStorage.get.mockReturnValue('[]');
    capturedRequestId = undefined;
    uuidCounter = 0;

    handler = new AcpPermissionHandler();
    Object.defineProperty(handler, 'logger', { value: mockLogger, writable: true });
    Object.defineProperty(handler, 'storageProvider', { value: mockStorageProvider, writable: true });
    Object.defineProperty(handler, 'preferenceService', { value: mockPreferenceService, writable: true });
    Object.defineProperty(handler, 'permissionStorage', { value: mockStorage, writable: true });
    // Prevent initStorage from overwriting mock storage
    Object.defineProperty(handler, 'ensureInitialized', { value: () => {}, writable: true });
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  describe('buildPermissionResponse()', () => {
    it('should build allow response', () => {
      const decision: PermissionDecision = { type: 'allow', optionId: 'opt-1', always: false };
      const result = handler.buildPermissionResponse(decision);

      expect(result).toEqual({
        outcome: { outcome: 'selected', optionId: 'opt-1' },
      });
    });

    it('should build reject response', () => {
      const decision: PermissionDecision = { type: 'reject', optionId: 'opt-2', always: true };
      const result = handler.buildPermissionResponse(decision);

      expect(result).toEqual({
        outcome: { outcome: 'selected', optionId: 'opt-2' },
      });
    });

    it('should build timeout response', () => {
      const decision: PermissionDecision = { type: 'timeout' };
      const result = handler.buildPermissionResponse(decision);

      expect(result).toEqual({
        outcome: { outcome: 'cancelled' },
      });
    });

    it('should build cancelled response', () => {
      const decision: PermissionDecision = { type: 'cancelled' };
      const result = handler.buildPermissionResponse(decision);

      expect(result).toEqual({
        outcome: { outcome: 'cancelled' },
      });
    });
  });

  describe('handleUserResponse()', () => {
    it('should resolve with allow for allow_once', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });

      // Use the captured request ID
      handler.handleUserResponse(capturedRequestId!, 'allow_once', 'allow_once');

      jest.advanceTimersByTime(0);

      const result = await decisionPromise;
      expect(result).toEqual({
        type: 'allow',
        optionId: 'allow_once',
        always: false,
      });
    });

    it('should resolve with reject for reject_once', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });

      handler.handleUserResponse(capturedRequestId!, 'reject_once', 'reject_once');

      jest.advanceTimersByTime(0);

      const result = await decisionPromise;
      expect(result).toEqual({
        type: 'reject',
        optionId: 'reject_once',
        always: false,
      });
    });

    it('should resolve with allow and always=true for allow_always', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });

      handler.handleUserResponse(capturedRequestId!, 'allow_always', 'allow_always');

      jest.advanceTimersByTime(0);

      const result = await decisionPromise;
      expect(result.type).toBe('allow');
      expect(result.always).toBe(true);
    });

    it('should resolve with reject and always=true for reject_always', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });

      handler.handleUserResponse(capturedRequestId!, 'reject_always', 'reject_always');

      jest.advanceTimersByTime(0);

      const result = await decisionPromise;
      expect(result.type).toBe('reject');
      expect(result.always).toBe(true);
    });

    it('should warn when requestId not found', () => {
      handler.handleUserResponse('non-existent-id', 'allow_once', 'allow_once');

      expect(mockLogger.warn).toHaveBeenCalledWith(expect.stringContaining('not found'));
    });

    it('should clear timeout when response is handled', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });

      handler.handleUserResponse(capturedRequestId!, 'allow_once', 'allow_once');
      jest.advanceTimersByTime(0);

      await decisionPromise;

      // Advance past the timeout - should not cause issues since timeout was cleared
      jest.advanceTimersByTime(6000);
    });

    it('should save rule when always option is chosen', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });

      handler.handleUserResponse(capturedRequestId!, 'allow_always', 'allow_always');

      jest.advanceTimersByTime(0);

      await decisionPromise;

      expect(mockStorage.set).toHaveBeenCalledWith('acp.permission.rules', expect.stringContaining('allow'));
    });
  });

  describe('cancelRequest()', () => {
    it('should resolve with cancelled when request exists', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });

      handler.cancelRequest(capturedRequestId!);
      jest.advanceTimersByTime(0);

      const result = await decisionPromise;
      expect(result).toEqual({ type: 'cancelled' });
    });

    it('should do nothing when requestId not found', () => {
      handler.cancelRequest('non-existent-id');
      // No error should be thrown
    });
  });

  describe('getRules()', () => {
    it('should return a copy of rules', () => {
      const rules1 = handler.getRules();
      const rules2 = handler.getRules();
      expect(rules1).toEqual(rules2);
      expect(rules1).not.toBe(rules2); // should be a copy
    });
  });

  describe('clearRules()', () => {
    it('should clear all rules and save', () => {
      handler.clearRules();

      expect(mockStorage.set).toHaveBeenCalledWith('acp.permission.rules', '[]');
    });
  });

  describe('removeRule()', () => {
    it('should remove a rule by id', async () => {
      const decisionPromise = handler.requestPermission({
        sessionId: 'sess-1',
        toolCall: { type: 'tool_call_update', title: 'Test tool', kind: 'write', content: '' } as any,
        options: [],
        timeout: 5000,
      });
      handler.handleUserResponse(capturedRequestId!, 'allow_always', 'allow_always');

      jest.advanceTimersByTime(0);
      await decisionPromise;

      const rules = handler.getRules();
      expect(rules.length).toBeGreaterThan(0);

      const ruleId = rules[0].id;
      handler.removeRule(ruleId);

      expect(handler.getRules()).toEqual([]);
    });

    it('should do nothing when rule id not found', () => {
      handler.removeRule('non-existent-rule-id');
      expect(handler.getRules()).toEqual([]);
    });
  });

  describe('auditLog()', () => {
    it('should log audit event', () => {
      handler.auditLog('request', {
        requestId: 'req-1',
        sessionId: 'sess-1',
        toolKind: 'write',
        toolTitle: 'Test tool',
      });

      expect(mockLogger.log).toHaveBeenCalledWith(
        expect.stringContaining('[ACP Permission Audit '),
        expect.any(Object),
      );
    });

    it('should log decision event with decision and reason', () => {
      handler.auditLog('decision', {
        requestId: 'req-1',
        sessionId: 'sess-1',
        decision: 'allow',
        reason: 'User approved',
      });

      expect(mockLogger.log).toHaveBeenCalledWith(
        expect.stringContaining('decision'),
        expect.objectContaining({
          requestId: 'req-1',
          decision: 'allow',
          reason: 'User approved',
        }),
      );
    });
  });
});
