import { BuiltinTheme } from '@opensumi/ide-theme';

export default {
  tokenColors: [
    {
      scope: ['meta.embedded', 'source.groovy.embedded'],
      settings: {
        foreground: '#D4D4D4',
      },
    },
    {
      scope: 'emphasis',
      settings: {
        fontStyle: 'italic',
      },
    },
    {
      scope: 'strong',
      settings: {
        fontStyle: 'bold',
      },
    },
    {
      scope: 'header',
      settings: {
        foreground: '#000080',
      },
    },
    {
      scope: 'comment',
      settings: {
        foreground: '#6A9955',
      },
    },
    {
      scope: 'constant.language',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: [
        'constant.numeric',
        'variable.other.enummember',
        'keyword.operator.plus.exponent',
        'keyword.operator.minus.exponent',
      ],
      settings: {
        foreground: '#b5cea8',
      },
    },
    {
      scope: 'constant.regexp',
      settings: {
        foreground: '#646695',
      },
    },
    {
      scope: 'entity.name.tag',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'entity.name.tag.css',
      settings: {
        foreground: '#d7ba7d',
      },
    },
    {
      scope: 'entity.other.attribute-name',
      settings: {
        foreground: '#9cdcfe',
      },
    },
    {
      scope: [
        'entity.other.attribute-name.class.css',
        'entity.other.attribute-name.class.mixin.css',
        'entity.other.attribute-name.id.css',
        'entity.other.attribute-name.parent-selector.css',
        'entity.other.attribute-name.pseudo-class.css',
        'entity.other.attribute-name.pseudo-element.css',
        'source.css.less entity.other.attribute-name.id',
        'entity.other.attribute-name.scss',
      ],
      settings: {
        foreground: '#d7ba7d',
      },
    },
    {
      scope: 'invalid',
      settings: {
        foreground: '#f44747',
      },
    },
    {
      scope: 'markup.underline',
      settings: {
        fontStyle: 'underline',
      },
    },
    {
      scope: 'markup.bold',
      settings: {
        fontStyle: 'bold',
        foreground: '#569cd6',
      },
    },
    {
      scope: 'markup.heading',
      settings: {
        fontStyle: 'bold',
        foreground: '#569cd6',
      },
    },
    {
      scope: 'markup.italic',
      settings: {
        fontStyle: 'italic',
      },
    },
    {
      scope: 'markup.inserted',
      settings: {
        foreground: '#b5cea8',
      },
    },
    {
      scope: 'markup.deleted',
      settings: {
        foreground: '#ce9178',
      },
    },
    {
      scope: 'markup.changed',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'punctuation.definition.quote.begin.markdown',
      settings: {
        foreground: '#6A9955',
      },
    },
    {
      scope: 'punctuation.definition.list.begin.markdown',
      settings: {
        foreground: '#6796e6',
      },
    },
    {
      scope: 'markup.inline.raw',
      settings: {
        foreground: '#ce9178',
      },
    },
    {
      name: 'brackets of XML/HTML tags',
      scope: 'punctuation.definition.tag',
      settings: {
        foreground: '#808080',
      },
    },
    {
      scope: ['meta.preprocessor', 'entity.name.function.preprocessor'],
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'meta.preprocessor.string',
      settings: {
        foreground: '#ce9178',
      },
    },
    {
      scope: 'meta.preprocessor.numeric',
      settings: {
        foreground: '#b5cea8',
      },
    },
    {
      scope: 'meta.structure.dictionary.key.python',
      settings: {
        foreground: '#9cdcfe',
      },
    },
    {
      scope: 'meta.diff.header',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'storage',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'storage.type',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: ['storage.modifier', 'keyword.operator.noexcept'],
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: ['string', 'meta.embedded.assembly'],
      settings: {
        foreground: '#ce9178',
      },
    },
    {
      scope: 'string.tag',
      settings: {
        foreground: '#ce9178',
      },
    },
    {
      scope: 'string.value',
      settings: {
        foreground: '#ce9178',
      },
    },
    {
      scope: 'string.regexp',
      settings: {
        foreground: '#d16969',
      },
    },
    {
      name: 'String interpolation',
      scope: [
        'punctuation.definition.template-expression.begin',
        'punctuation.definition.template-expression.end',
        'punctuation.section.embedded',
      ],
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      name: 'Reset JavaScript string interpolation expression',
      scope: ['meta.template.expression'],
      settings: {
        foreground: '#d4d4d4',
      },
    },
    {
      scope: [
        'support.type.vendored.property-name',
        'support.type.property-name',
        'variable.css',
        'variable.scss',
        'variable.other.less',
        'source.coffee.embedded',
      ],
      settings: {
        foreground: '#9cdcfe',
      },
    },
    {
      scope: 'keyword',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'keyword.control',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'keyword.operator',
      settings: {
        foreground: '#d4d4d4',
      },
    },
    {
      scope: [
        'keyword.operator.new',
        'keyword.operator.expression',
        'keyword.operator.cast',
        'keyword.operator.sizeof',
        'keyword.operator.alignof',
        'keyword.operator.typeid',
        'keyword.operator.alignas',
        'keyword.operator.instanceof',
        'keyword.operator.logical.python',
        'keyword.operator.wordlike',
      ],
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'keyword.other.unit',
      settings: {
        foreground: '#b5cea8',
      },
    },
    {
      scope: ['punctuation.section.embedded.begin.php', 'punctuation.section.embedded.end.php'],
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'support.function.git-rebase',
      settings: {
        foreground: '#9cdcfe',
      },
    },
    {
      scope: 'constant.sha.git-rebase',
      settings: {
        foreground: '#b5cea8',
      },
    },
    {
      name: 'coloring of the Java import and package identifiers',
      scope: ['storage.modifier.import.java', 'variable.language.wildcard.java', 'storage.modifier.package.java'],
      settings: {
        foreground: '#d4d4d4',
      },
    },
    {
      name: 'this.self',
      scope: 'variable.language',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      name: 'Function declarations',
      scope: [
        'entity.name.function',
        'support.function',
        'support.constant.handlebars',
        'source.powershell variable.other.member',
        'entity.name.operator.custom-literal', // See https://en.cppreference.com/w/cpp/language/user_literal
      ],
      settings: {
        foreground: '#DCDCAA',
      },
    },
    {
      name: 'Types declaration and references',
      scope: [
        'meta.return-type',
        'support.class',
        'support.type',
        'entity.name.type',
        'entity.name.namespace',
        'entity.other.attribute',
        'entity.name.scope-resolution',
        'entity.name.class',
        'storage.type.numeric.go',
        'storage.type.byte.go',
        'storage.type.boolean.go',
        'storage.type.string.go',
        'storage.type.uintptr.go',
        'storage.type.error.go',
        'storage.type.rune.go',
        'storage.type.cs',
        'storage.type.generic.cs',
        'storage.type.modifier.cs',
        'storage.type.variable.cs',
        'storage.type.annotation.java',
        'storage.type.generic.java',
        'storage.type.java',
        'storage.type.object.array.java',
        'storage.type.primitive.array.java',
        'storage.type.primitive.java',
        'storage.type.token.java',
        'storage.type.groovy',
        'storage.type.annotation.groovy',
        'storage.type.parameters.groovy',
        'storage.type.generic.groovy',
        'storage.type.object.array.groovy',
        'storage.type.primitive.array.groovy',
        'storage.type.primitive.groovy',
      ],
      settings: {
        foreground: '#4EC9B0',
      },
    },
    {
      name: 'Types declaration and references, TS grammar specific',
      scope: [
        'meta.type.cast.expr',
        'meta.type.new.expr',
        'support.constant.math',
        'support.constant.dom',
        'support.constant.json',
        'entity.other.inherited-class',
      ],
      settings: {
        foreground: '#4EC9B0',
      },
    },
    {
      name: 'Control flow / Special keywords',
      scope: [
        'keyword.control',
        'source.cpp keyword.operator.new',
        'keyword.operator.delete',
        'keyword.other.using',
        'keyword.other.operator',
        'entity.name.operator',
      ],
      settings: {
        foreground: '#C586C0',
      },
    },
    {
      name: 'Variable and parameter name',
      scope: [
        'variable',
        'meta.definition.variable.name',
        'support.variable',
        'entity.nam1e.variable',
        'constant.other.placeholder', // placeholders in strings
      ],
      settings: {
        foreground: '#9CDCFE',
      },
    },
    {
      name: 'Constants and enums',
      scope: ['variable.other.constant', 'variable.other.enummember'],
      settings: {
        foreground: '#4FC1FF',
      },
    },
    {
      name: 'Object keys, TS grammar specific',
      scope: ['meta.object-literal.key'],
      settings: {
        foreground: '#9CDCFE',
      },
    },
    {
      name: 'CSS property value',
      scope: [
        'support.constant.property-value',
        'support.constant.font-name',
        'support.constant.media-type',
        'support.constant.media',
        'constant.other.color.rgb-value',
        'constant.other.rgb-value',
        'support.constant.color',
      ],
      settings: {
        foreground: '#CE9178',
      },
    },
    {
      name: 'Regular expression groups',
      scope: [
        'punctuation.definition.group.regexp',
        'punctuation.definition.group.assertion.regexp',
        'punctuation.definition.character-class.regexp',
        'punctuation.character.set.begin.regexp',
        'punctuation.character.set.end.regexp',
        'keyword.operator.negation.regexp',
        'support.other.parenthesis.regexp',
      ],
      settings: {
        foreground: '#CE9178',
      },
    },
    {
      scope: [
        'constant.character.character-class.regexp',
        'constant.other.character-class.set.regexp',
        'constant.other.character-class.regexp',
        'constant.character.set.regexp',
      ],
      settings: {
        foreground: '#d16969',
      },
    },
    {
      scope: ['keyword.operator.or.regexp', 'keyword.control.anchor.regexp'],
      settings: {
        foreground: '#DCDCAA',
      },
    },
    {
      scope: 'keyword.operator.quantifier.regexp',
      settings: {
        foreground: '#d7ba7d',
      },
    },
    {
      scope: 'constant.character',
      settings: {
        foreground: '#569cd6',
      },
    },
    {
      scope: 'constant.character.escape',
      settings: {
        foreground: '#d7ba7d',
      },
    },
    {
      scope: 'entity.name.label',
      settings: {
        foreground: '#C8C8C8',
      },
    },
  ],
  colors: {
    'activityBar.activeBorder': '#ffffff1f',
    'activityBar.activeForeground': '#FFFFFF',
    'activityBar.background': '#00000000',
    'activityBar.border': '#252729',
    'activityBar.disableForeground': '#5F656B',
    'activityBar.dropBackground': '#43484D',
    'activityBar.foreground': '#fff',
    'activityBar.inactiveForeground': '#ffffff73',
    'activityBarBadge.background': '#167CDB',
    'activityBarBadge.foreground': '#FFFFFF',
    'badge.background': '#FFFFFF40',
    'badge.foreground': '#D7DBDE',
    'breadcrumb.background': '#222830',
    'breadcrumb.foreground': '#ffffff73',
    'checkbox.background': '#ffffff14',
    'checkbox.border': '#ffffff1f',
    descriptionForeground: '#868C91',
    'diffEditor.insertedTextBackground': '#12A7A740',
    'editorGroup.border': '#43484D',
    'editorGroup.dropBackground': '#5F656B40',
    'editorGroup.emptyBackground': '#00000000',
    'editorGroupHeader.tabsBackground': '#222830',
    'editorSuggestWidget.selectedBackground': '#1A66AC',
    errorForeground: '#D21F28',
    focusBorder: '#ffffff1f',
    foreground: '#D7DBDE',
    'editorCommentsWidget.unresolvedBorder': '#ffffff',
    'gitDecoration.addedResourceForeground': '#8FD460',
    'gitDecoration.conflictingResourceForeground': '#7F9EF3',
    'gitDecoration.deletedResourceForeground': '#F3956A',
    'gitDecoration.ignoredResourceForeground': '#BBC0C4',
    'gitDecoration.modifiedResourceForeground': '#F3CC62',
    'gitDecoration.submoduleResourceForeground': '#67ABEB',
    'gitDecoration.untrackedResourceForeground': '#58D1C9',
    'icon.foreground': '#D7DBDE',
    'input.background': '#ffffff14',
    'input.foreground': '#d7dbde',
    'input.placeholderForeground': '#ffffff59',
    'inputDropdown.searchMatchForeground': '#3895EB',
    'inputIcon.foreground': '#5F656B',
    'inputValidation.errorBackground': '#321115',
    'inputValidation.errorBorder': '#D21F28',
    'inputValidation.errorForeground': '#D7DBDE',
    'inputValidation.errorText': '#D21F28',
    'inputValidation.warningBackground': '#332510',
    'inputValidation.warningBorder': '#DBA936',
    'inputValidation.warningText': '#DBA936',
    'inputValidation.warningForeground': '#d7dbde',
    'keybinding.background': '#5F656B33',
    'kt.accentForeground': '#FFFFFF',
    'kt.actionbar.disableForeground': '#5F656B',
    'kt.actionbar.foreground': '#D7DBDE',
    'kt.actionbar.selectionBorder': '#1A66AC',
    'kt.actionbar.separatorBackground': '#5F656B40',
    'kt.activityBar.dropUpBackground': '#1F507D',
    'kt.button.disableBackground': '#5F656B40',
    'kt.button.disableBorder': '#5F656B80',
    'kt.button.disableForeground': '#5F656B',
    'kt.checkbox.disableBackground': '#5F656B40',
    'kt.checkbox.disableForeground': '#5F656B',
    'kt.checkbox.hoverBorder': '#167CDB',
    'kt.checkbox.selectionBackground': '#167CDB',
    'kt.checkbox.selectionForeground': '#FFFFFF',
    'kt.dangerButton.background': '#DB4345',
    'kt.dangerButton.clickBackground': '#D21F28',
    'kt.dangerButton.foreground': '#FFFFFF',
    'kt.dangerButton.hoverBackground': '#F37370',
    'kt.dangerGhostButton.border': '#DB4345',
    'kt.dangerGhostButton.clickBorder': '#D21F28',
    'kt.dangerGhostButton.clickForeground': '#D21F28',
    'kt.dangerGhostButton.foreground': '#DB4345',
    'kt.dangerGhostButton.hoverBorder': '#F37370',
    'kt.dangerGhostButton.hoverForeground': '#F37370',
    'kt.defaultButton.background': '#ffffff14',
    'kt.defaultButton.border': '#00000000',
    'kt.defaultButton.clickBackground': '#ffffff14',
    'kt.defaultButton.clickBorder': '#00000000',
    'kt.defaultButton.disableBackground': '#ffffff14',
    'kt.defaultButton.disableBorder': '#00000000',
    'kt.defaultButton.disableForeground': '#ffffff40',
    'kt.defaultButton.foreground': '#D7DBDE',
    'kt.defaultButton.hoverBackground': '#ffffff29',
    'kt.defaultButton.hoverBorder': '#00000000',
    'kt.defaultButton.selectionBackground': '#ffffff29',
    'kt.defaultButton.selectionForeground': '#fff',
    'kt.dirtyDot.foreground': '#868C91',
    'kt.disableForeground': '#5F656B',
    'kt.editorBreadcrumb.borderDown': '#e9e9e914',
    'kt.errorBackground': '#D21F2840',
    'kt.errorIconForeground': '#DB4345',
    'kt.hintBackground': '#5F656B40',
    'kt.hintIconForeground': '#868C91',
    'kt.icon.clickForeground': '#D7DBDE',
    'kt.icon.disableForeground': '#5F656B',
    'kt.icon.foreground': '#ffffff73',
    'kt.icon.hoverBackground': '#ffffff14',
    'kt.icon.hoverForeground': '#D7DBDE',
    'kt.icon.secondaryForeground': '#868C91',
    'kt.infoBackground': '#167CDB40',
    'kt.infoIconForeground': '#3895EB',
    'kt.input.border': '#00000000',
    'kt.input.disableBackground': '#5F656B40',
    'kt.input.disableForeground': '#ffffff40',
    'kt.input.selectionBackground': '#1A66AC',
    'kt.linkButton.clickForeground': '#167CDB',
    'kt.linkButton.disableForeground': '#5F656B',
    'kt.linkButton.foreground': '#3895EB',
    'kt.linkButton.hoverForeground': '#67ABEB',
    'kt.menu.descriptionForeground': '#868C91',
    'kt.menu.disableForeground': '#5F656B',
    'kt.menubar.background': '#00000000',
    'kt.menubar.border': '#252729',
    'kt.menubar.foreground': '#D7DBDE',
    'kt.menubar.separatorBackground': '#5F656B40',
    'kt.modal.background': '#222830',
    'kt.modal.foreground': '#D7DBDE',
    'kt.modal.separatorBackground': '#2C3033',
    'kt.modalErrorIcon.foreground': '#DB4345',
    'kt.modalInfoIcon.foreground': '#3895EB',
    'kt.modalSuccessIcon.foreground': '#64B436',
    'kt.modalWarningIcon.foreground': '#DBA936',
    'kt.panel.secondaryForeground': '#868C91',
    'kt.panelTab.activeBackground': '#151b21',
    'kt.panelTab.activeForeground': '#FFFFFF',
    'kt.panelTab.border': '#ffffff1f',
    'kt.panelTab.inactiveBackground': '#00000000',
    'kt.panelTab.inactiveForeground': '#D7DBDE',
    'kt.panelTitle.background': '#222830',
    'kt.popover.background': '#2b333d',
    'kt.popover.border': '#363940',
    'kt.popover.foreground': '#fffffff2',
    'kt.popover.prominentBackground': '#2C3033',
    'kt.primaryButton.background': '#3c8dff',
    'kt.primaryButton.clickBackground': '#3c8dffa6',
    'kt.primaryButton.foreground': '#fff',
    'kt.primaryButton.hoverBackground': '#3c8dffa6',
    'kt.primaryButton.border': '#00000000',
    'kt.primaryGhostButton.clickBorder': '#3c8dff',
    'kt.primaryGhostButton.clickForeground': '#167CDB',
    'kt.primaryGhostButton.clickBackground': '#00000000',
    'kt.primaryGhostButton.foreground': '#3895EB',
    'kt.primaryGhostButton.border': '#3c8dff',
    'kt.primaryGhostButton.background': '#00000000',
    'kt.secondaryButton.border': '#5F656B',
    'kt.secondaryButton.clickBorder': '#167CDB',
    'kt.secondaryButton.clickForeground': '#167CDB',
    'kt.secondaryButton.foreground': '#D7DBDE',
    'kt.secondaryButton.hoverBorder': '#3895EB',
    'kt.secondaryButton.hoverForeground': '#3895EB',
    'kt.secondaryButton.background': '#00000000',
    'kt.select.background': '#ffffff14',
    'kt.select.border': '#00000000',
    'kt.select.disableBackground': '#5F656B40',
    'kt.select.disableForeground': '#5F656B',
    'kt.select.foreground': '#D7DBDE',
    'kt.select.placeholderForeground': '#5F656B',
    'kt.selectDropdown.background': '#222830',
    'kt.selectDropdown.foreground': '#D7DBDE',
    'kt.selectDropdown.hoverBackground': '#ffffff14',
    'kt.selectDropdown.selectionBackground': '#ffffff14',
    'kt.selectOption.activeBorder': '#167CDB',
    'kt.statusbar.offline.background': '#DB4345',
    'kt.successBackground': '#48A91840',
    'kt.successIconForeground': '#64B436',
    'kt.tab.activeBorder': '#167CDB',
    'kt.tab.activeForeground': '#FFFFFF',
    'kt.tab.borderDown': '#5F656B40',
    'kt.tab.inactiveForeground': '#D7DBDE',
    'kt.tree.activeSelectionBackground': '#1A66AC',
    'kt.tree.activeSelectionForeground': '#FFFFFF',
    'kt.tree.hoverBackground': '#5F656B40',
    'kt.tree.hoverForeground': '#D7DBDE',
    'kt.tree.inactiveSelectionBackground': '#ffffff1f',
    'kt.tree.inactiveSelectionForeground': '#fff',
    'kt.warningBackground': '#D7951340',
    'kt.warningIconForeground': '#DBA936',
    'kt.whiteGhostButton.border': '#FFFFFF',
    'kt.whiteGhostButton.clickBorder': '#FFFFFFA6',
    'kt.whiteGhostButton.clickForeground': '#FFFFFFA6',
    'kt.whiteGhostButton.disableBackground': '#FFFFFF03',
    'kt.whiteGhostButton.disableBorder': '#FFFFFF40',
    'kt.whiteGhostButton.disableForeground': '#FFFFFF40',
    'kt.whiteGhostButton.foreground': '#FFFFFF',
    'list.activeSelectionBackground': '#1A66AC',
    'list.activeSelectionForeground': '#e1e4e8',
    'list.evenItemBackground': '#5F656B14',
    'list.headerBackground': '#5F656B1F',
    'list.hoverBackground': '#5F656B40',
    'menu.background': '#222830d9',
    'menu.foreground': '#D7DBDE',
    'menu.selectionBackground': '#5F656B40',
    'menu.selectionForeground': '#FFFFFF',
    'menu.separatorBackground': '#43484D',
    'menubar.selectionBackground': '#5f656b40',
    'menubar.selectionForeground': '#FFFFFF',
    'message.background': '#222830',
    'message.foreground': '#D7DBDE',
    'messageErrorIcon.foreground': '#DB4345',
    'messageInfoIcon.foreground': '#3895EB',
    'messageSuccessIcon.foreground': '#64B436',
    'messageWarningIcon.foreground': '#DBA936',
    'notifications.background': '#222830',
    'notifications.foreground': '#D7DBDE',
    'notificationsErrorIcon.foreground': '#DB4345',
    'notificationsInfoIcon.foreground': '#3895EB',
    'notificationsWarningIcon.foreground': '#DBA936',
    'panel.background': '#151b21',
    'panel.border': '#43484D',
    'panel.foreground': '#D7DBDE',
    'panel.selectionBackground': '#5F656B40',
    'panel.separatorBackground': '#2C3033',
    'panelMenuBadge.background': '#00000040',
    'panelMenuBar.background': '#2C3033',
    'panelMenuBarBadge.foreground': '#5F656B40',
    'panelTabBarActionIcon.Background': '#868C91',
    'panelTabBarError.foreground': '#DB4345',
    'panelTitle.activeBorder': '#167CDB',
    'panelTitle.activeForeground': '#FFFFFF',
    'panelTitle.hoverForeground': '#FFFFFF',
    'panelTitle.inactiveForeground': '#ffffff73',
    'selectDropdown.descriptionForeground': '#868C91',
    'selectDropdown.teamForeground': '#868C91',
    'sideBar.background': '#00000000',
    'sideBar.border': '#ffffff1f',
    'sideBar.dropBackground': '#43484D',
    'sideBar.dropUpBackground': '#1F507D',
    'sideBarSectionHeader.background': '#00000000',
    'sideBarSectionHeader.foreground': '#ffffffa6',
    'sideBarTitle.foreground': '#FFFFFF',
    'statusBar.background': '#00000000',
    'statusBar.debuggingBackground': '#D77915',
    'statusBar.foreground': '#ffffff73',
    'statusBar.noFolderBackground': '#43484D',
    'statusBarItem.activeBackground': '#FFFFFF40',
    'statusBarItem.hoverBackground': '#FFFFFF03',
    'statusBarItem.remoteBackground': '#3c8dff',
    'statusBarItem.prominentForeground': '#d2d2d2a6',
    'statusBarItem.prominentBackground': '#2a2a2a80',
    'tab.activeBackground': '#151b21',
    'tab.activeForeground': '#FFFFFF',
    'tab.border': '#e9e9e914',
    'tab.inactiveBackground': '#00000000',
    'tab.inactiveForeground': '#ffffff73',
    'tab.hoverBackground': '#00000000',
    'tab.unfocusedActiveBackground': '#202224',
    'tab.unfocusedActiveForeground': '#868C91',
    'tab.unfocusedInactiveForeground': '#868C91',
    'terminal.background': '#151b21',
    'terminal.border': '#252729',
    'terminal.foreground': '#D7DBDE',
    'terminal.offlineBackground': '#D21F2840',
    'terminal.offlineForeground': '#868C91',
    'terminal.offlineLinkForeground': '#3895EB',
    'terminal.selectionBackground': '#5F656B40',
    'tooltip.background': '#35393D',
    'tooltip.foreground': '#D7DBDE',
    'widget.shadow': '#00000099',
    'list.focusOutline': '#00000000',
    'editorInlayHint.parameterBackground': '#00000000',
    'button.background': '#ffffff14',
    'scrollbarSlider.background': '#ffffff14',
    'editor.background': '#181818',
    'quickInput.background': '#222830',
    'list.focusBackground': '#ffffff1f',
    'textLink.foreground': '#3c8dff',
    'editorStickyScroll.background': '#151b21',
  },
  semanticHighlighting: true,
  semanticTokenColors: {
    newOperator: '#d4d4d4',
    stringLiteral: '#ce9178',
    customLiteral: '#D4D4D4',
    numberLiteral: '#b5cea8',
  },
  encodedTokensColors: [],
  rules: [],
  base: 'vs-dark' as BuiltinTheme,
  designThemeType: 'design-dark',
  inherit: true,
  hasDefaultTokens: false,
  id: 'opensumi-design-dark-theme',
  name: 'OpenSumi Design Dark+ (default dark)',
};
