export enum EDITOR_BROWSER_COMMANDS  {
  openResource = 'editor.openUri',
  saveCurrent = 'editor.saveCurrent',
  compare = 'editor.compare',
  close = 'editor.close',
  closeAllInGroup = 'editor.closeAllInGroup',
  closeToRight = 'editor.closeToRight',
  getCurrent = 'editor.getCurrent',
  splitToLeft = 'editor.splitToLeft',
  splitToRight = 'editor.splitToRight',
  splitToTop = 'editor.splitToTop',
  splitToBottom = 'editor.splitToBottom',
  changeLanguage = 'editor.changeLanguage',
  changeEncoding = 'editor.changeEncoding',
  changeEol = 'editor.changeEol',
}
