// opensumi 内product主题图标class名需和vscode做一个兼容对应
// 图标对应
// otcicon ?
export const defaultProductIcons = {
  'accounts-view-bar-icon': 'accounts-view-bar-icon',
  'breakpoints-activate': 'breakpoints-activate',
  'breakpoints-remove-all': 'breakpoints-remove-all',
  'breakpoints-view-icon': 'breakpoints-view-icon',
  'callhierarchy-incoming': 'callhierarchy-incoming',
  'callhierarchy-outgoing': 'callhierarchy-outgoing',
  'callstack-view-icon': 'callstack-view-icon',
  'callstack-view-session': 'callstack-view-session',
  'comments-view-icon': 'comments-view-icon',
  'debug-breakpoint': 'debug-breakpoint',
  'debug-breakpoint-conditional': 'debug-breakpoint-conditional',
  'debug-breakpoint-conditional-disabled': 'debug-breakpoint-conditional-disabled',
  'debug-breakpoint-conditional-unverified': 'debug-breakpoint-conditional-unverified',
  'debug-breakpoint-data': 'debug-breakpoint-data',
  'debug-breakpoint-data-disabled': 'debug-breakpoint-data-disabled',
  'debug-breakpoint-data-unverified': 'debug-breakpoint-data-unverified',
  'debug-breakpoint-disabled': 'debug-breakpoint-disabled',
  'debug-breakpoint-function': 'debug-breakpoint-function',
  'debug-breakpoint-function-disabled': 'debug-breakpoint-function-disabled',
  'debug-breakpoint-function-unverified': 'debug-breakpoint-function-unverified',
  'debug-breakpoint-log': 'debug-breakpoint-log',
  'debug-breakpoint-log-disabled': 'debug-breakpoint-log-disabled',
  'debug-breakpoint-log-unverified': 'debug-breakpoint-log-unverified',
  'debug-breakpoint-unsupported': 'debug-breakpoint-unsupported',
  'debug-breakpoint-unverified': 'debug-breakpoint-unverified',
  'debug-collapse-all': 'debug-collapse-all',
  'debug-configure': 'debug-configure',
  'debug-console': 'debug-console',
  'debug-console-clear-all': 'debug-console-clear-all',
  'debug-console-evaluation-input': 'debug-console-evaluation-input',
  'debug-console-evaluation-prompt': 'debug-console-evaluation-prompt',
  'debug-console-view-icon': 'debug-console-view-icon',
  'debug-continue': 'debug-continue',
  'debug-disconnect': 'debug-disconnect',
  'debug-gripper': 'debug-gripper',
  'debug-hint': 'debug-hint',
  'debug-pause': 'debug-pause',
  'debug-restart': 'debug-restart',
  'debug-restart-frame': 'debug-restart-frame',
  'debug-reverse-continue': 'debug-reverse-continue',
  'debug-stackframe': 'debug-stackframe',
  'debug-stackframe-focused': 'debug-stackframe-focused',
  'debug-start': 'debug-start',
  'debug-step-back': 'debug-step-back',
  'debug-step-into': 'debug-step-into',
  'debug-step-out': 'debug-step-out',
  'debug-step-over': 'debug-step-over',
  'debug-stop': 'debug-stop',
  'default-view-icon': 'default-view-icon',
  'diff-editor-next-change': 'diff-editor-next-change',
  'diff-editor-previous-change': 'diff-editor-previous-change',
  'diff-editor-toggle-whitespace': 'diff-editor-toggle-whitespace',
  'diff-insert': 'diff-insert',
  'diff-remove': 'diff-remove',
  'diff-review-close': 'diff-review-close',
  'diff-review-insert': 'diff-review-insert',
  'diff-review-remove': 'diff-review-remove',
  'explorer-view-icon': 'kticon-explorer',
  'extensions-clear-search-results': 'extensions-clear-search-results',
  'extensions-configure-recommended': 'extensions-configure-recommended',
  'extensions-filter': 'extensions-filter',
  'extensions-info-message': 'extensions-info-message',
  'extensions-install-count': 'extensions-install-count',
  'extensions-install-local-in-remote': 'extensions-install-local-in-remote',
  'extensions-install-workspace-recommended': 'extensions-install-workspace-recommended',
  'extensions-manage': 'extensions-manage',
  'extensions-rating': 'extensions-rating',
  'extensions-refresh': 'extensions-refresh',
  'extensions-remote': 'extensions-remote',
  'extensions-star-empty': 'extensions-star-empty',
  'extensions-star-full': 'extensions-star-full',
  'extensions-star-half': 'extensions-star-half',
  'extensions-sync-enabled': 'extensions-sync-enabled',
  'extensions-sync-ignored': 'extensions-sync-ignored',
  'extensions-view-icon': 'extensions-view-icon',
  'extensions-warning-message': 'extensions-warning-message',
  'find-collapsed': 'find-collapsed',
  'find-expanded': 'find-expanded',
  'find-next-match': 'find-next-match',
  'find-previous-match': 'find-previous-match',
  'find-replace': 'find-replace',
  'find-replace-all': 'find-replace-all',
  'find-selection': 'find-selection',
  'folding-collapsed': 'folding-collapsed',
  'folding-expanded': 'folding-expanded',
  'getting-started-beginner': 'getting-started-beginner',
  'getting-started-codespaces': 'getting-started-codespaces',
  'getting-started-item-checked': 'getting-started-item-checked',
  'getting-started-item-unchecked': 'getting-started-item-unchecked',
  'getting-started-setup': 'getting-started-setup',
  'goto-next-location': 'goto-next-location',
  'goto-previous-location': 'goto-previous-location',
  'keybindings-add': 'keybindings-add',
  'keybindings-edit': 'keybindings-edit',
  'keybindings-record-keys': 'keybindings-record-keys',
  'keybindings-sort': 'keybindings-sort',
  'loaded-scripts-view-icon': 'loaded-scripts-view-icon',
  'marker-navigation-next': 'marker-navigation-next',
  'marker-navigation-previous': 'marker-navigation-previous',
  'markers-view-filter': 'markers-view-filter',
  'markers-view-icon': 'markers-view-icon',
  'markers-view-multi-line-collapsed': 'markers-view-multi-line-collapsed',
  'markers-view-multi-line-expanded': 'markers-view-multi-line-expanded',
  'notebook-clear': 'notebook-clear',
  'notebook-collapsed': 'notebook-collapsed',
  'notebook-delete-cell': 'notebook-delete-cell',
  'notebook-edit': 'notebook-edit',
  'notebook-execute': 'notebook-execute',
  'notebook-execute-all': 'notebook-execute-all',
  'notebook-expanded': 'notebook-expanded',
  'notebook-kernel-configure': 'notebook-kernel-configure',
  'notebook-kernel-select': 'notebook-kernel-select',
  'notebook-mimetype': 'notebook-mimetype',
  'notebook-move-down': 'notebook-move-down',
  'notebook-move-up': 'notebook-move-up',
  'notebook-open-as-text': 'notebook-open-as-text',
  'notebook-render-output': 'notebook-render-output',
  'notebook-revert': 'notebook-revert',
  'notebook-split-cell': 'notebook-split-cell',
  'notebook-state-error': 'notebook-state-error',
  'notebook-state-success': 'notebook-state-success',
  'notebook-stop': 'notebook-stop',
  'notebook-stop-edit': 'notebook-stop-edit',
  'notebook-unfold': 'notebook-unfold',
  'notifications-clear': 'notifications-clear',
  'notifications-clear-all': 'notifications-clear-all',
  'notifications-collapse': 'notifications-collapse',
  'notifications-configure': 'notifications-configure',
  'notifications-expand': 'notifications-expand',
  'notifications-hide': 'notifications-hide',
  'open-editors-view-icon': 'open-editors-view-icon',
  'outline-view-icon': 'outline-view-icon',
  'output-view-icon': 'output-view-icon',
  'panel-close': 'panel-close',
  'panel-maximize': 'panel-maximize',
  'panel-restore': 'panel-restore',
  'parameter-hints-next': 'parameter-hints-next',
  'parameter-hints-previous': 'parameter-hints-previous',
  'ports-forward-icon': 'ports-forward-icon',
  'ports-open-browser-icon': 'ports-open-browser-icon',
  'ports-stop-forward-icon': 'ports-stop-forward-icon',
  'ports-view-icon': 'ports-view-icon',
  'preferences-clear-input': 'preferences-clear-input',
  'preferences-open-settings': 'preferences-open-settings',
  'private-ports-view-icon': 'private-ports-view-icon',
  'public-ports-view-icon': 'public-ports-view-icon',
  'refactor-preview-view-icon': 'refactor-preview-view-icon',
  'remote-explorer-documentation': 'remote-explorer-documentation',
  'remote-explorer-feedback': 'remote-explorer-feedback',
  'remote-explorer-get-started': 'remote-explorer-get-started',
  'remote-explorer-report-issues': 'remote-explorer-report-issues',
  'remote-explorer-review-issues': 'remote-explorer-review-issues',
  'remote-explorer-view-icon': 'remote-explorer-view-icon',
  'review-comment-collapse': 'review-comment-collapse',
  'run-view-icon': 'run-view-icon',
  'search-clear-results': 'search-clear-results',
  'search-collapse-results': 'search-collapse-results',
  'search-details': 'search-details',
  'search-expand-results': 'search-expand-results',
  'search-hide-replace': 'search-hide-replace',
  'search-new-editor': 'search-new-editor',
  'search-refresh': 'search-refresh',
  'search-remove': 'search-remove',
  'search-replace': 'search-replace',
  'search-replace-all': 'search-replace-all',
  'search-show-context': 'search-show-context',
  'search-show-replace': 'search-show-replace',
  'search-stop': 'search-stop',
  'search-view-icon': 'kticon-search',
  'settings-add': 'settings-add',
  'settings-discard': 'settings-discard',
  'settings-edit': 'settings-edit',
  'settings-folder-dropdown': 'settings-folder-dropdown',
  'settings-group-collapsed': 'settings-group-collapsed',
  'settings-group-expanded': 'settings-group-expanded',
  'settings-more-action': 'settings-more-action',
  'settings-remove': 'settings-remove',
  'settings-sync-view-icon': 'settings-sync-view-icon',
  'settings-view-bar-icon': 'settings-view-bar-icon',
  'source-control-view-icon': 'source-control-view-icon',
  'suggest-more-info': 'suggest-more-info',
  'tasks-list-configure': 'tasks-list-configure',
  'tasks-remove': 'tasks-remove',
  'terminal-kill': 'terminal-kill',
  'terminal-new': 'terminal-new',
  'terminal-rename': 'terminal-rename',
  'terminal-view-icon': 'terminal-view-icon',
  'test-view-icon': 'test-view-icon',
  'testing-cancel-icon': 'testing-cancel-icon',
  'testing-debug-icon': 'testing-debug-icon',
  'testing-error-icon': 'testing-error-icon',
  'testing-failed-icon': 'testing-failed-icon',
  'testing-passed-icon': 'testing-passed-icon',
  'testing-queued-icon': 'testing-queued-icon',
  'testing-run-all-icon': 'testing-run-all-icon',
  'testing-run-icon': 'testing-run-icon',
  'testing-show-as-list-icon': 'testing-show-as-list-icon',
  'testing-skipped-icon': 'testing-skipped-icon',
  'testing-unset-icon': 'testing-unset-icon',
  'timeline-open': 'timeline-open',
  'timeline-pin': 'timeline-pin',
  'timeline-refresh': 'timeline-refresh',
  'timeline-unpin': 'timeline-unpin',
  'timeline-view-icon': 'timeline-view-icon',
  'variables-view-icon': 'variables-view-icon',
  'view-pane-container-collapsed': 'view-pane-container-collapsed',
  'view-pane-container-expanded': 'view-pane-container-expanded',
  'watch-expressions-add': 'watch-expressions-add',
  'watch-expressions-add-function-breakpoint': 'watch-expressions-add-function-breakpoint',
  'watch-expressions-remove-all': 'watch-expressions-remove-all',
  'watch-view-icon': 'watch-view-icon',
  'widget-close': 'widget-close',
};

// v0.0.27
export const codIconNames = [
  'add',
  'plus',
  'gist-new',
  'repo-create',
  'lightbulb',
  'light-bulb',
  'repo',
  'repo-delete',
  'gist-fork',
  'repo-forked',
  'git-pull-request',
  'git-pull-request-abandoned',
  'record-keys',
  'keyboard',
  'tag',
  'tag-add',
  'tag-remove',
  'person',
  'person-follow',
  'person-outline',
  'person-filled',
  'git-branch',
  'git-branch-create',
  'git-branch-delete',
  'source-control',
  'mirror',
  'mirror-public',
  'star',
  'star-add',
  'star-delete',
  'star-empty',
  'comment',
  'comment-add',
  'alert',
  'warning',
  'search',
  'search-save',
  'log-out',
  'sign-out',
  'log-in',
  'sign-in',
  'eye',
  'eye-unwatch',
  'eye-watch',
  'circle-filled',
  'primitive-dot',
  'close-dirty',
  'debug-breakpoint',
  'debug-breakpoint-disabled',
  'debug-hint',
  'primitive-square',
  'edit',
  'pencil',
  'info',
  'issue-opened',
  'gist-private',
  'git-fork-private',
  'lock',
  'mirror-private',
  'close',
  'remove-close',
  'x',
  'repo-sync',
  'sync',
  'clone',
  'desktop-download',
  'beaker',
  'microscope',
  'vm',
  'device-desktop',
  'file',
  'file-text',
  'more',
  'ellipsis',
  'kebab-horizontal',
  'mail-reply',
  'reply',
  'organization',
  'organization-filled',
  'organization-outline',
  'new-file',
  'file-add',
  'new-folder',
  'file-directory-create',
  'trash',
  'trashcan',
  'history',
  'clock',
  'folder',
  'file-directory',
  'symbol-folder',
  'logo-github',
  'mark-github',
  'github',
  'terminal',
  'console',
  'repl',
  'zap',
  'symbol-event',
  'error',
  'stop',
  'variable',
  'symbol-variable',
  'array',
  'symbol-array',
  'symbol-module',
  'symbol-package',
  'symbol-namespace',
  'symbol-object',
  'symbol-method',
  'symbol-function',
  'symbol-constructor',
  'symbol-boolean',
  'symbol-null',
  'symbol-numeric',
  'symbol-number',
  'symbol-structure',
  'symbol-struct',
  'symbol-parameter',
  'symbol-type-parameter',
  'symbol-key',
  'symbol-text',
  'symbol-reference',
  'go-to-file',
  'symbol-enum',
  'symbol-value',
  'symbol-ruler',
  'symbol-unit',
  'activate-breakpoints',
  'archive',
  'arrow-both',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-small-down',
  'arrow-small-left',
  'arrow-small-right',
  'arrow-small-up',
  'arrow-up',
  'bell',
  'bold',
  'book',
  'bookmark',
  'debug-breakpoint-conditional-unverified',
  'debug-breakpoint-conditional',
  'debug-breakpoint-conditional-disabled',
  'debug-breakpoint-data-unverified',
  'debug-breakpoint-data',
  'debug-breakpoint-data-disabled',
  'debug-breakpoint-log-unverified',
  'debug-breakpoint-log',
  'debug-breakpoint-log-disabled',
  'briefcase',
  'broadcast',
  'browser',
  'bug',
  'calendar',
  'case-sensitive',
  'check',
  'checklist',
  'chevron-down',
  'drop-down-button',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chrome-close',
  'chrome-maximize',
  'chrome-minimize',
  'chrome-restore',
  'circle',
  'circle-outline',
  'debug-breakpoint-unverified',
  'circle-slash',
  'circuit-board',
  'clear-all',
  'clippy',
  'close-all',
  'cloud-download',
  'cloud-upload',
  'code',
  'collapse-all',
  'color-mode',
  'comment-discussion',
  'compare-changes',
  'credit-card',
  'dash',
  'dashboard',
  'database',
  'debug-continue',
  'debug-disconnect',
  'debug-pause',
  'debug-restart',
  'debug-start',
  'debug-step-into',
  'debug-step-out',
  'debug-step-over',
  'debug-stop',
  'debug',
  'device-camera-video',
  'device-camera',
  'device-mobile',
  'diff-added',
  'diff-ignored',
  'diff-modified',
  'diff-removed',
  'diff-renamed',
  'diff',
  'discard',
  'editor-layout',
  'empty-window',
  'exclude',
  'extensions',
  'eye-closed',
  'file-binary',
  'file-code',
  'file-media',
  'file-pdf',
  'file-submodule',
  'file-symlink-directory',
  'file-symlink-file',
  'file-zip',
  'files',
  'filter',
  'flame',
  'fold-down',
  'fold-up',
  'fold',
  'folder-active',
  'folder-opened',
  'gear',
  'gift',
  'gist-secret',
  'gist',
  'git-commit',
  'git-compare',
  'git-merge',
  'github-action',
  'github-alt',
  'globe',
  'grabber',
  'graph',
  'gripper',
  'heart',
  'home',
  'horizontal-rule',
  'hubot',
  'inbox',
  'issue-closed',
  'issue-reopened',
  'issues',
  'italic',
  'jersey',
  'json',
  'kebab-vertical',
  'key',
  'law',
  'lightbulb-autofix',
  'link-external',
  'link',
  'list-ordered',
  'list-unordered',
  'live-share',
  'loading',
  'location',
  'mail-read',
  'mail',
  'markdown',
  'megaphone',
  'mention',
  'milestone',
  'mortar-board',
  'move',
  'multiple-windows',
  'mute',
  'no-newline',
  'note',
  'octoface',
  'open-preview',
  'package',
  'paintcan',
  'pin',
  'play',
  'run',
  'plug',
  'preserve-case',
  'preview',
  'project',
  'pulse',
  'question',
  'quote',
  'radio-tower',
  'reactions',
  'references',
  'refresh',
  'regex',
  'remote-explorer',
  'remote',
  'remove',
  'replace-all',
  'replace',
  'repo-clone',
  'repo-force-push',
  'repo-pull',
  'repo-push',
  'report',
  'request-changes',
  'rocket',
  'root-folder-opened',
  'root-folder',
  'rss',
  'ruby',
  'save-all',
  'save-as',
  'save',
  'screen-full',
  'screen-normal',
  'search-stop',
  'server',
  'settings-gear',
  'settings',
  'shield',
  'smiley',
  'sort-precedence',
  'split-horizontal',
  'split-vertical',
  'squirrel',
  'star-full',
  'star-half',
  'symbol-class',
  'symbol-color',
  'symbol-customcolor',
  'symbol-constant',
  'symbol-enum-member',
  'symbol-field',
  'symbol-file',
  'symbol-interface',
  'symbol-keyword',
  'symbol-misc',
  'symbol-operator',
  'symbol-property',
  'wrench',
  'wrench-subaction',
  'symbol-snippet',
  'tasklist',
  'telescope',
  'text-size',
  'three-bars',
  'thumbsdown',
  'thumbsup',
  'tools',
  'triangle-down',
  'triangle-left',
  'triangle-right',
  'triangle-up',
  'twitter',
  'unfold',
  'unlock',
  'unmute',
  'unverified',
  'verified',
  'versions',
  'vm-active',
  'vm-outline',
  'vm-running',
  'watch',
  'whitespace',
  'whole-word',
  'window',
  'word-wrap',
  'zoom-in',
  'zoom-out',
  'list-filter',
  'list-flat',
  'list-selection',
  'selection',
  'list-tree',
  'debug-breakpoint-function-unverified',
  'debug-breakpoint-function',
  'debug-breakpoint-function-disabled',
  'debug-stackframe-active',
  'circle-small-filled',
  'debug-stackframe-dot',
  'debug-stackframe',
  'debug-stackframe-focused',
  'debug-breakpoint-unsupported',
  'symbol-string',
  'debug-reverse-continue',
  'debug-step-back',
  'debug-restart-frame',
  'call-incoming',
  'call-outgoing',
  'menu',
  'expand-all',
  'feedback',
  'group-by-ref-type',
  'ungroup-by-ref-type',
  'account',
  'bell-dot',
  'debug-console',
  'library',
  'output',
  'run-all',
  'sync-ignored',
  'pinned',
  'github-inverted',
  'debug-alt',
  'server-process',
  'server-environment',
  'pass',
  'stop-circle',
  'play-circle',
  'record',
  'debug-alt-small',
  'vm-connect',
  'cloud',
  'merge',
  'export',
  'graph-left',
  'magnet',
  'notebook',
  'redo',
  'check-all',
  'pinned-dirty',
  'pass-filled',
  'circle-large-filled',
  'circle-large',
  'circle-large-outline',
  'combine',
  'gather',
  'table',
  'variable-group',
  'type-hierarchy',
  'type-hierarchy-sub',
  'type-hierarchy-super',
  'git-pull-request-create',
  'run-above',
  'run-below',
  'notebook-template',
  'debug-rerun',
  'workspace-trusted',
  'workspace-untrusted',
  'workspace-unspecified',
  'terminal-cmd',
  'terminal-debian',
  'terminal-linux',
  'terminal-powershell',
  'terminal-tmux',
  'terminal-ubuntu',
  'terminal-bash',
  'arrow-swap',
  'copy',
  'person-add',
  'filter-filled',
  'wand',
  'debug-line-by-line',
  'inspect',
  'layers',
  'layers-dot',
  'layers-active',
  'compass',
  'compass-dot',
  'compass-active',
  'azure',
  'issue-draft',
  'git-pull-request-closed',
  'git-pull-request-draft',
  'debug-all',
  'debug-coverage',
  'run-errors',
  'folder-library',
  'debug-continue-small',
  'beaker-stop',
  'graph-line',
  'graph-scatter',
  'pie-chart',
  'bracket',
  'bracket-dot',
  'bracket-error',
  'lock-small',
  'azure-devops',
  'verified-filled',
  'newline',
  'layout',
  'layout-activitybar-left',
  'layout-activitybar-right',
  'layout-panel-left',
  'layout-panel-center',
  'layout-panel-justify',
  'layout-panel-right',
  'layout-panel',
  'layout-sidebar-left',
  'layout-sidebar-right',
  'layout-statusbar',
  'layout-menubar',
  'layout-centered',
  'layout-sidebar-right-off',
  'layout-panel-off',
  'layout-sidebar-left-off',
  'target',
  'indent',
  'record-small',
  'error-small',
  'arrow-circle-down',
  'arrow-circle-left',
  'arrow-circle-right',
  'arrow-circle-up',
  'heart-filled',
  'map',
  'map-filled',
  'circle-small',
  'bell-slash',
  'bell-slash-dot',
  'comment-unresolved',
  'git-pull-request-go-to-changes',
  'git-pull-request-new-changes',
  'search-fuzzy',
  'dialog-error',
  'dialog-warning',
  'dialog-info',
  'dialog-close',
  'tree-item-expanded',
  'tree-filter-on-type-on',
  'tree-filter-on-type-off',
  'tree-filter-clear',
  'tree-item-loading',
  'menu-selection',
  'menu-submenu',
  'menubar-more',
  'scrollbar-button-left',
  'scrollbar-button-right',
  'scrollbar-button-up',
  'scrollbar-button-down',
  'toolbar-more',
  'quick-input-back',
  'widget-close',
  'goto-previous-location',
  'goto-next-location',
  'diff-review-insert',
  'diff-review-remove',
  'diff-review-close',
  'diff-insert',
  'diff-remove',
  'suggest-more-info',
  'marker-navigation-next',
  'marker-navigation-previous',
  'find-selection',
  'find-collapsed',
  'find-expanded',
  'find-replace',
  'find-replace-all',
  'find-previous-match',
  'find-next-match',
  'folding-expanded',
  'folding-collapsed',
  'folding-manual-collapsed',
  'folding-manual-expanded',
  'parameter-hints-next',
  'parameter-hints-previous',
  'extensions-warning-message',
];

export const ktIconNames = [
  'arrow-down',
  'arrow-right',
  'loading',
  'window',
  'revoke',
  'doubleleft',
  'bash',
  'python',
  'kotlin',
  'zsh',
  'arrowleft',
  'arrowright',
  'hex',
  'node',
  'git',
  'rust',
  'java',
  'vim',
  'brew',
  'go',
  'debug-alt-small',
  'filter',
  'test',
  'debug-restart-frame',
  'unmax',
  'max',
  'close1',
  'min',
  'focus',
  'experiment',
  'expand-all',
  'tree',
  'toolkit',
  'check-square-o',
  'time-circle',
  'add-comments',
  'deploy',
  'Gitlab-fill',
  'message',
  'mobile-phone',
  'PR',
  'file-copy',
  'project-information',
  'control',
  'doubleright',
  'mobile',
  'retrieval',
  'openfile',
  'arrowup',
  'arrowdown',
  'code',
  'keyboard',
  'breakpoint-stop-before',
  'breakpoint-activate',
  'breakpoint-enabled',
  'breakpoint-disabled',
  'breakpoint-deactivate',
  'breakpoint-stop',
  'pause',
  'stop',
  'share',
  'drag',
  'check-close-circle-o',
  'question-circle-o',
  'open-changes',
  'terminal',
  'editor',
  'start',
  'step-in',
  'continue',
  'step-out',
  'reload',
  'step',
  'folder-default',
  'file-default',
  'dock-down',
  'gitlab',
  'minus',
  'layout',
  'layout1',
  'expand',
  'shrink',
  'sever',
  'more',
  'embed',
  'dock-right',
  'undock',
  'error',
  'browser-preview',
  'follow-cursor',
  'github-fill',
  'global-search',
  'content-search',
  'repository',
  'link',
  'left',
  'down',
  'download',
  'edit',
  'disconnect',
  'left-right-subfield',
  'up-down-subfield',
  'deactivate-breakpoints',
  'activate-breakpoints',
  'window-maximize',
  'caret-right',
  'info-circle',
  'close-circle',
  'warning-circle',
  'explorer',
  'save-all',
  'close-all',
  'replace',
  'eye-close',
  'open',
  'collapse-all',
  'rollback',
  'clear',
  'line',
  'close_square',
  'ab',
  'abl',
  'refresh',
  'folder',
  'new-folder',
  'new-file',
  'regex',
  'cloud-download',
  'fullscreen',
  'fullscreen-exit',
  'plus',
  'eye',
  'wait',
  'search',
  'scm',
  'debug',
  'extension',
  'question-circle',
  'sync',
  'detail',
  'delete',
  'check',
  'check-circle-fill',
  'close-circle-fill',
  'info-circle-fill',
  'file-exclamation',
  'branches',
  'up',
  'swap',
  'unorderedlist',
  'close',
  'smile',
  'setting',
  'team',
  'file-text',
  'bell',
  'cloud-server',
  'right',
  'ellipsis',
];

const ktIconPrefix = 'kticon-';

const codIconPrefix = 'codicon-';

const sumiIconPrefix = 'sumiicon-';

/*
 * Opensumi 三套主题图标
 * kticon   默认主题图标
 * codicon  兼容 vscode 侧图标 monaco内使用
 * octicon  vscode 已废弃的图标库
 * 为兼容三套图标库，需要做一个映射 将 kticon 以及 codicon 做对应 octicon 后面废弃暂时不做处理
 */

export const codIcon2ktIcon = {
  'arrow-left': 'arrowleft',
  'arrow-right': 'arrowright',
  'arrow-up': 'arrowup',
  'arrow-down': 'arrowdown',
  'chevron-left': 'left',
  'chevron-right': 'right',
  'chevron-up': 'up',
  'chevron-down': 'down',
  files: 'explorer',
  search: 'search',
  loading: 'loading',
  '': '',
};
