name: Pull Request Review By ChatGPT

on:
  pull_request:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  code-review:
    if: ${{ OPENAI_API_KEY }}
    name: Code Review
    runs-on: ubuntu-latest
    steps:
      - uses: opensumi/actions/.github/actions/code-review@main
