name: Pull Request Review By ChatGPT

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    name: Code Review
    runs-on: ubuntu-latest

    steps:
      # 判断用户是否有写仓库权限
      - name: 'Check User Permission'
        uses: 'lannonbr/repo-permission-check-action@2.0.0'
        with:
          permission: 'write'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: opensumi/actions/bot-token@main
        with:
          token-server: ${{ secrets.BOT_TOKEN_SERVER }}
          flag: ${{ secrets.BOT_FLAG }}
      - uses: opensumi/actions/.github/actions/code-review@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
